#!/bin/bash -l
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 1
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 2
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 3
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 4
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 5
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 6
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 7
/scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/StrepLab-JanOw_SPN-Typer.sh /scicomp/groups/OID/NCIRD-OD/OI/ncbs/team/GABRIEL/Strep_Container/GitLabDir/strep-containerization/Spn_Scripts_Reference/finaltest.out/ 8
